name: Dev build

on: [ push, workflow_dispatch ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        uses: AutoModality/action-clean@v1.1.0

      - name: Clone project
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: dev-${{ github.sha }}
          name: ${{ github.event.head_commit.message }} (${{ github.sha }})
          files: |
            build/libs/keiko-plugin-inspector-all.jar
